//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""Rod"",
            ""id"": ""b3370059-b24f-477c-a252-104719c21cf0"",
            ""actions"": [
                {
                    ""name"": ""ThrowHook"",
                    ""type"": ""Value"",
                    ""id"": ""41c5502a-81fa-46ca-8eba-0f903ea7b300"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollingUp"",
                    ""type"": ""Value"",
                    ""id"": ""0bcf68ef-646d-4d94-aae7-3f20794851d2"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FightWithFish"",
                    ""type"": ""Value"",
                    ""id"": ""b60ccea7-c471-46ec-935e-2ca71d3198b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c211d161-10dd-4792-81a1-de9ba02a3ba1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8389e807-945d-4020-aa02-fa97378fa73b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollingUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""A/D Move"",
                    ""id"": ""9353b908-f809-424e-9d8b-6af0e017f98d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""07dcfeac-2640-4f2f-b506-9e560cbec828"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""489b0bc9-1d6e-4dd7-903d-9911980179e7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left/Right Move"",
                    ""id"": ""e49f6411-5768-488d-ae16-130cf1249282"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""53fe8884-79ab-4c8a-a253-30d7bf4bcec2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""05338526-94bf-4ad0-bcc3-33b137081e8f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FightWithFish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""56d71515-79c6-451a-9cb6-f7a800775110"",
            ""actions"": [
                {
                    ""name"": ""OpenCataloge"",
                    ""type"": ""Button"",
                    ""id"": ""10882122-28f2-45fe-b2e7-119e90d59fe9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenShop"",
                    ""type"": ""Button"",
                    ""id"": ""c8c559cc-0436-4927-830e-5cb902d92221"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""272f54ad-5805-40de-90ec-4d9fe0b55155"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a3144b9-87cd-4148-8932-64d96cbecd73"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCataloge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c37a1b07-d2cc-4bbf-99c6-75c3dd60c8b6"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenShop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd912b29-c248-4aba-9c81-ba5ca4e9c0fb"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FishSeller"",
            ""id"": ""18c15e4a-5dcb-4c34-9a67-6574074b5a68"",
            ""actions"": [
                {
                    ""name"": ""ClikckOnFishSeller"",
                    ""type"": ""Button"",
                    ""id"": ""3ac619b6-b8f2-45e7-83d4-e645a6c9b55f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""91c0fdfb-1b62-4290-bcf2-76e0bf7589f7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""872d3cc1-0aa5-4468-96ec-0666c258f172"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClikckOnFishSeller"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e6ce022-60eb-455b-b874-b7dd4d02d271"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PAC-MAN"",
            ""id"": ""01d7560d-c7ed-4284-bbae-69ca98e4f371"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""73895a16-67f8-4c87-ac6d-4d064bcf22fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""53a34c8a-4c56-47b8-816e-932992fec580"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""73575f1e-396f-4220-a381-691083776be9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48bf2c56-6be4-4687-865c-8835e5e5d959"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ebc75b0c-02de-4ea1-a6a1-56832afd97b0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4f342a8d-4411-4e33-b48c-cc563be7203b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Rod
        m_Rod = asset.FindActionMap("Rod", throwIfNotFound: true);
        m_Rod_ThrowHook = m_Rod.FindAction("ThrowHook", throwIfNotFound: true);
        m_Rod_RollingUp = m_Rod.FindAction("RollingUp", throwIfNotFound: true);
        m_Rod_FightWithFish = m_Rod.FindAction("FightWithFish", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_OpenCataloge = m_UI.FindAction("OpenCataloge", throwIfNotFound: true);
        m_UI_OpenShop = m_UI.FindAction("OpenShop", throwIfNotFound: true);
        m_UI_MousePosition = m_UI.FindAction("MousePosition", throwIfNotFound: true);
        // FishSeller
        m_FishSeller = asset.FindActionMap("FishSeller", throwIfNotFound: true);
        m_FishSeller_ClikckOnFishSeller = m_FishSeller.FindAction("ClikckOnFishSeller", throwIfNotFound: true);
        m_FishSeller_MousePosition = m_FishSeller.FindAction("MousePosition", throwIfNotFound: true);
        // PAC-MAN
        m_PACMAN = asset.FindActionMap("PAC-MAN", throwIfNotFound: true);
        m_PACMAN_Move = m_PACMAN.FindAction("Move", throwIfNotFound: true);
    }

    ~@PlayerAction()
    {
        UnityEngine.Debug.Assert(!m_Rod.enabled, "This will cause a leak and performance issues, PlayerAction.Rod.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayerAction.UI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FishSeller.enabled, "This will cause a leak and performance issues, PlayerAction.FishSeller.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PACMAN.enabled, "This will cause a leak and performance issues, PlayerAction.PACMAN.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Rod
    private readonly InputActionMap m_Rod;
    private List<IRodActions> m_RodActionsCallbackInterfaces = new List<IRodActions>();
    private readonly InputAction m_Rod_ThrowHook;
    private readonly InputAction m_Rod_RollingUp;
    private readonly InputAction m_Rod_FightWithFish;
    public struct RodActions
    {
        private @PlayerAction m_Wrapper;
        public RodActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ThrowHook => m_Wrapper.m_Rod_ThrowHook;
        public InputAction @RollingUp => m_Wrapper.m_Rod_RollingUp;
        public InputAction @FightWithFish => m_Wrapper.m_Rod_FightWithFish;
        public InputActionMap Get() { return m_Wrapper.m_Rod; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RodActions set) { return set.Get(); }
        public void AddCallbacks(IRodActions instance)
        {
            if (instance == null || m_Wrapper.m_RodActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RodActionsCallbackInterfaces.Add(instance);
            @ThrowHook.started += instance.OnThrowHook;
            @ThrowHook.performed += instance.OnThrowHook;
            @ThrowHook.canceled += instance.OnThrowHook;
            @RollingUp.started += instance.OnRollingUp;
            @RollingUp.performed += instance.OnRollingUp;
            @RollingUp.canceled += instance.OnRollingUp;
            @FightWithFish.started += instance.OnFightWithFish;
            @FightWithFish.performed += instance.OnFightWithFish;
            @FightWithFish.canceled += instance.OnFightWithFish;
        }

        private void UnregisterCallbacks(IRodActions instance)
        {
            @ThrowHook.started -= instance.OnThrowHook;
            @ThrowHook.performed -= instance.OnThrowHook;
            @ThrowHook.canceled -= instance.OnThrowHook;
            @RollingUp.started -= instance.OnRollingUp;
            @RollingUp.performed -= instance.OnRollingUp;
            @RollingUp.canceled -= instance.OnRollingUp;
            @FightWithFish.started -= instance.OnFightWithFish;
            @FightWithFish.performed -= instance.OnFightWithFish;
            @FightWithFish.canceled -= instance.OnFightWithFish;
        }

        public void RemoveCallbacks(IRodActions instance)
        {
            if (m_Wrapper.m_RodActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRodActions instance)
        {
            foreach (var item in m_Wrapper.m_RodActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RodActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RodActions @Rod => new RodActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_OpenCataloge;
    private readonly InputAction m_UI_OpenShop;
    private readonly InputAction m_UI_MousePosition;
    public struct UIActions
    {
        private @PlayerAction m_Wrapper;
        public UIActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenCataloge => m_Wrapper.m_UI_OpenCataloge;
        public InputAction @OpenShop => m_Wrapper.m_UI_OpenShop;
        public InputAction @MousePosition => m_Wrapper.m_UI_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @OpenCataloge.started += instance.OnOpenCataloge;
            @OpenCataloge.performed += instance.OnOpenCataloge;
            @OpenCataloge.canceled += instance.OnOpenCataloge;
            @OpenShop.started += instance.OnOpenShop;
            @OpenShop.performed += instance.OnOpenShop;
            @OpenShop.canceled += instance.OnOpenShop;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @OpenCataloge.started -= instance.OnOpenCataloge;
            @OpenCataloge.performed -= instance.OnOpenCataloge;
            @OpenCataloge.canceled -= instance.OnOpenCataloge;
            @OpenShop.started -= instance.OnOpenShop;
            @OpenShop.performed -= instance.OnOpenShop;
            @OpenShop.canceled -= instance.OnOpenShop;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // FishSeller
    private readonly InputActionMap m_FishSeller;
    private List<IFishSellerActions> m_FishSellerActionsCallbackInterfaces = new List<IFishSellerActions>();
    private readonly InputAction m_FishSeller_ClikckOnFishSeller;
    private readonly InputAction m_FishSeller_MousePosition;
    public struct FishSellerActions
    {
        private @PlayerAction m_Wrapper;
        public FishSellerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClikckOnFishSeller => m_Wrapper.m_FishSeller_ClikckOnFishSeller;
        public InputAction @MousePosition => m_Wrapper.m_FishSeller_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_FishSeller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FishSellerActions set) { return set.Get(); }
        public void AddCallbacks(IFishSellerActions instance)
        {
            if (instance == null || m_Wrapper.m_FishSellerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FishSellerActionsCallbackInterfaces.Add(instance);
            @ClikckOnFishSeller.started += instance.OnClikckOnFishSeller;
            @ClikckOnFishSeller.performed += instance.OnClikckOnFishSeller;
            @ClikckOnFishSeller.canceled += instance.OnClikckOnFishSeller;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IFishSellerActions instance)
        {
            @ClikckOnFishSeller.started -= instance.OnClikckOnFishSeller;
            @ClikckOnFishSeller.performed -= instance.OnClikckOnFishSeller;
            @ClikckOnFishSeller.canceled -= instance.OnClikckOnFishSeller;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IFishSellerActions instance)
        {
            if (m_Wrapper.m_FishSellerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFishSellerActions instance)
        {
            foreach (var item in m_Wrapper.m_FishSellerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FishSellerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FishSellerActions @FishSeller => new FishSellerActions(this);

    // PAC-MAN
    private readonly InputActionMap m_PACMAN;
    private List<IPACMANActions> m_PACMANActionsCallbackInterfaces = new List<IPACMANActions>();
    private readonly InputAction m_PACMAN_Move;
    public struct PACMANActions
    {
        private @PlayerAction m_Wrapper;
        public PACMANActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PACMAN_Move;
        public InputActionMap Get() { return m_Wrapper.m_PACMAN; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PACMANActions set) { return set.Get(); }
        public void AddCallbacks(IPACMANActions instance)
        {
            if (instance == null || m_Wrapper.m_PACMANActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PACMANActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPACMANActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPACMANActions instance)
        {
            if (m_Wrapper.m_PACMANActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPACMANActions instance)
        {
            foreach (var item in m_Wrapper.m_PACMANActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PACMANActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PACMANActions @PACMAN => new PACMANActions(this);
    public interface IRodActions
    {
        void OnThrowHook(InputAction.CallbackContext context);
        void OnRollingUp(InputAction.CallbackContext context);
        void OnFightWithFish(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnOpenCataloge(InputAction.CallbackContext context);
        void OnOpenShop(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
    public interface IFishSellerActions
    {
        void OnClikckOnFishSeller(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
    public interface IPACMANActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
